<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExtraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('poblacion')->where('numdoc', '1001379400')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003047651')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003062982')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003066914')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003071318')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003072592')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003073416')->update(['cargo' => 'AUXILIAR DE   APOYO DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1003140072')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003178045')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003187735')->update(['cargo' => 'AUXILIAR DE RECURSOS HUMANOS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1003187820')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003187867')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003189145')->update(['cargo' => 'AUXILIAR DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1003189711')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003192871')->update(['cargo' => 'AUXILIAR DE RECURSOS HUMANOS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1003393546')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003395208')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003395258')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003396114')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003397094')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003403148')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003403178')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003403666')->update(['cargo' => 'AUXILIAR DE COMPRAS Y MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003434033')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003451869')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003591024')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003715848')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1003719951')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1007675576')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1007765660')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1014263860')->update(['cargo' => 'AUXILIAR CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1026299689')->update(['cargo' => 'AUXILIAR CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1028013581')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1028019342')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1040749973')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1043443281')->update(['cargo' => 'SUPERNUMERARIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1053789849')->update(['cargo' => 'GERENTE GENERAL', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1062680161')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1062956529')->update(['cargo' => 'AUXILIAR DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1062958210')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063138788')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063140271')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063141895')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063161860')->update(['cargo' => 'AUXILIAR DE  SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063168591')->update(['cargo' => 'RECEPCIONISTA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063291171')->update(['cargo' => 'ANALISTA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1063294105')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063295103')->update(['cargo' => 'DISE?ADOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063304546')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1063308123')->update(['cargo' => 'AUXILIAR DE RECURSOS HUMANOS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1064309726')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1064985812')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1064988807')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1064992626')->update(['cargo' => 'COORDINADOR DE TRABAJO  SEGURO EN ALTURAS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1064993901')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1064998492')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1064999641')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065004059')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065011216')->update(['cargo' => 'AUXILIAR DE LOTERIAS DE CENTROS DE COSTOS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065012025')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065012063')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065013030')->update(['cargo' => 'INSTALADOR   DE ANTENAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1065373397')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1066178507')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1066529014')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1066722131')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1066738788')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1066752188')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067837633')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067839000')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067843962')->update(['cargo' => 'ASISTENTE CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067851034')->update(['cargo' => 'AUXILIAR DE  ESCRUTINIO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067851371')->update(['cargo' => 'COORDINACION OPERATIVA', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1067852205')->update(['cargo' => 'SUPERNUMERARIO A', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067853596')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067855603')->update(['cargo' => 'AUXILIAR CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067858315')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067858380')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067859113')->update(['cargo' => 'AUXILIAR DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067861540')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067865004')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067871104')->update(['cargo' => 'COORDINADOR DE GIROS', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1067872711')->update(['cargo' => 'COORDINADOR DE COMUNICACIONES', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1067880383')->update(['cargo' => 'ADMINISTRADOR BASES DE DATOS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067881454')->update(['cargo' => 'COORDINADOR DE TRABAJO  SEGURO EN ALTURAS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067887836')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067894579')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067895409')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067896660')->update(['cargo' => 'AUXILIAR DE LOTERIAS DE CENTROS DE COSTOS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067897404')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067900075')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067901589')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067903248')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067907392')->update(['cargo' => 'AUXILIAR DE ESCRUTINIO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067907810')->update(['cargo' => 'INSTALADOR   DE ANTENAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067910977')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067913684')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067914598')->update(['cargo' => 'AUXILIAR DE TESORERIA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067916158')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067917120')->update(['cargo' => 'AUXILIAR DE   APOYO DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067919341')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067919527')->update(['cargo' => 'COORDINADOR DE TANGIBLES', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1067924247')->update(['cargo' => 'AUXILIAR DE LOTERIAS DE CENTROS DE COSTOS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067924795')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067926933')->update(['cargo' => 'TRADE MARKETING', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067927294')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067927543')->update(['cargo' => 'AUXILIAR DE COMPRAS Y MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067927674')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067927714')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067930675')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067931906')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067931909')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067932000')->update(['cargo' => 'AUXILIAR DE ESCRUTINIO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067933451')->update(['cargo' => 'ASISTENTE CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067936497')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067941727')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067942330')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067942897')->update(['cargo' => 'ASISTENTE  GESTION HUMANA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067944262')->update(['cargo' => 'LIDER CORRESPONSAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067946081')->update(['cargo' => 'LIDER DE SERVICIO AL CLIENTE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067946210')->update(['cargo' => 'ANALISTA RPA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067947211')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067948380')->update(['cargo' => 'AUXILIAR DE LOTERIAS DE CENTROS DE COSTOS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067949819')->update(['cargo' => 'COMUNITY MANAGER', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067952258')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067956530')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067957572')->update(['cargo' => 'DESARROLLADOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067958066')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067959233')->update(['cargo' => 'AUXILIAR DE RECURSOS HUMANOS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1067960086')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067961099')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067962209')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067963054')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1067968174')->update(['cargo' => 'AUXILIAR DE COMUNICACION', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1068417547')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1068660804')->update(['cargo' => 'AUXILIAR DE LOGISTICAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1068662346')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1068669140')->update(['cargo' => 'INSTALADOR   DE ANTENAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1069475724')->update(['cargo' => 'ADMINISTRADOR DE ZONA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1069497813')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1069499921')->update(['cargo' => 'RECEPCIONISTA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1070809388')->update(['cargo' => 'INSTALADOR   DE ANTENAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1071354710')->update(['cargo' => 'ASISTENTE DE TESORERIA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1072252173')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1073809692')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1073811252')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1073814641')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1073821379')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1073980543')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1074002195')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1074003547')->update(['cargo' => 'TESORERO AUXILIAR', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '10765762')->update(['cargo' => 'COORDINADOR DE NUEVOS CANALES', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '10769024')->update(['cargo' => 'COORDINADOR DE TRABAJO  SEGURO EN ALTURAS', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '10771962')->update(['cargo' => 'ELECTRICISTA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '10774461')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '10781102')->update(['cargo' => 'TESORERO AUXILIAR', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '10782357')->update(['cargo' => 'JEFE DE MANTENIMIENTO', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '10782938')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1082965409')->update(['cargo' => 'COORDINADOR APUESTAS BETPLAY', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '10967405')->update(['cargo' => 'COORDINADOR APUESTAS BETPLAY', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '11000591')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '11003315')->update(['cargo' => 'ASISTENTE DE ESCRUTINIO', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '11032293')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '11061889')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1110513536')->update(['cargo' => 'ANALISTA RPA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '1112762595')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1113658735')->update(['cargo' => 'JEFE DE VENTAS', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1128055156')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1128469600')->update(['cargo' => 'COORDINADOR DE   CONVENIOS', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '1129484982')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1129516769')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1133871178')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1143140188')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1192776747')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1192790452')->update(['cargo' => 'AUXILIAR DE ESCRUTINIO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1193459646')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1196963547')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1232889043')->update(['cargo' => 'CAPACITADOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1233338109')->update(['cargo' => 'AUXILIAR DE LOGISTICAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1233338258')->update(['cargo' => 'CAPACITADOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '1233910055')->update(['cargo' => 'CAPACITADOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '15031287')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '15043713')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '15517507')->update(['cargo' => 'JEFE DE  APLICACIONES', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '15664786')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '22477190')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25767386')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25773648')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25785065')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25785503')->update(['cargo' => 'ASISTENTE CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '25786936')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25799802')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25799843')->update(['cargo' => 'AUXILIAR CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '25800699')->update(['cargo' => 'AUXILIAR DE SISTEMAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25801360')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25801687')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25801792')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25808179')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25845547')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25852599')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25857796')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25868195')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25872767')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25872966')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25876617')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25912134')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '25914085')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26000806')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26038990')->update(['cargo' => 'TESORERO AUXILIAR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26039678')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26040994')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26147562')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26161982')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26162683')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26162720')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26175528')->update(['cargo' => 'AUXILIAR DE  SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26176594')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26176599')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26176693')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26201549')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26201746')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26202622')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26203784')->update(['cargo' => 'ASISTENTE DE TESORERIA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26215622')->update(['cargo' => 'ASISTENTE CONTABLE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '26215737')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '26226822')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30567813')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30569747')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30572179')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30573604')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30575138')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30576655')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30582043')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30651695')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30664035')->update(['cargo' => 'JEFE DE COMPRAS', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '30686236')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '30689671')->update(['cargo' => 'TESORERO AUXILIAR', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '30690030')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '32746958')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '33335954')->update(['cargo' => 'TESORERO AUXILIAR', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '34974820')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '34978365')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '34993787')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '34997503')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35005526')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35113527')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35114531')->update(['cargo' => 'AUXILIAR DE TESORERIA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35115771')->update(['cargo' => 'IMPLEMENTACIONES', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '35116309')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35116885')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '35117440')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '35143564')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '37725644')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '43262816')->update(['cargo' => 'AUXILIAR DE TESORERIA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '43623359')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '43803250')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '44005803')->update(['cargo' => 'JURIDICO', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '45693129')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50571478')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50848152')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50848234')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50848988')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50849039')->update(['cargo' => 'JEFE DE CARTERA', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '50850714')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50850786')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50861689')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '50868221')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50879021')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50879327')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50881654')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50890446')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50891554')->update(['cargo' => 'AUXILIAR DE  SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50892433')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50894451')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50894612')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50894843')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50895044')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50898520')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50898608')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50899295')->update(['cargo' => 'AUXILIAR DE  SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50899398')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50901131')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50902582')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50902659')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50903334')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50903692')->update(['cargo' => 'AUXILIAR DE VENTAS', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50904027')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50904737')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50908460')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50908862')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50912530')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50913466')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50913891')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50914823')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50915009')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50915110')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50915875')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50918514')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50919993')->update(['cargo' => 'JEFE DE TESORERIA', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '50920638')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50921025')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50921178')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50922401')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50922460')->update(['cargo' => 'AUXILIAR DE AUDITORIA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '50922591')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50925090')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50927049')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50928094')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50928973')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50929726')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50930005')->update(['cargo' => 'AUXILIAR CONTABLE', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50931804')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50931979')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50933008')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50934775')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50935223')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50935815')->update(['cargo' => 'COORDINADOR TRADE MARKETING', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '50937136')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50937793')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50938282')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50939262')->update(['cargo' => 'ASISTENTE DE  VENTAS Y SERVICIO AL CLIENTE', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '50939344')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50939440')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50941435')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50949180')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50953401')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50955958')->update(['cargo' => 'AUDITORA GENERAL', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '50959992')->update(['cargo' => 'JEFE  SIG', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '50960065')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50966919')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50967203')->update(['cargo' => 'AUXILIAR DE SERVICIOS GENERALES', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50967771')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50983637')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50984452')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50984486')->update(['cargo' => 'AUXILIAR DE OFICINA', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50989752')->update(['cargo' => 'ASESOR COMERCIAL BETPLAY', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '50995469')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '52042715')->update(['cargo' => 'DIRECTOR DE GESTION HUMANA', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '52126523')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '52706961')->update(['cargo' => 'DIRECTOR ADMINISTRATIVO Y FINANCIERO', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '64569460')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '6879270')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '6883361')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '72220073')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '7384497')->update(['cargo' => 'ADMINISTRADOR DE ZONA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '75145718')->update(['cargo' => 'JEFE DE MERCADEO', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '78022211')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78029058')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78031567')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78075815')->update(['cargo' => 'OFICIAL DE CUMPLIMIENTO', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '78380389')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78689789')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78690358')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78692165')->update(['cargo' => 'ASESOR COMERCIAL', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78695892')->update(['cargo' => 'CAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78702219')->update(['cargo' => 'MENSAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78714343')->update(['cargo' => 'MENSAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78715066')->update(['cargo' => 'ADMINISTRADOR DE CENTRO DE COSTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78715473')->update(['cargo' => 'JEFE DE  TELECOMUNICACIONES  E INFRAESTRUCTURA', 'rol' => 'ESTRATEGICO']);
		DB::table('poblacion')->where('numdoc', '78726201')->update(['cargo' => 'ADMINISTRADOR DE ZONA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '78735472')->update(['cargo' => 'LIDER COMERCIAL', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '78744999')->update(['cargo' => 'AUXILIAR MANTENIMIENTO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78746109')->update(['cargo' => 'MENSAJERO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78747008')->update(['cargo' => 'COORDINADOR DE ZONA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '78752750')->update(['cargo' => 'AUXILIAR  OPERATIVO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '78757441')->update(['cargo' => 'ADMINISTRADOR DE ZONA', 'rol' => 'ASISTENCIAL']);
		DB::table('poblacion')->where('numdoc', '78768740')->update(['cargo' => 'SOPORTE TECNICO', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '79679586')->update(['cargo' => 'CONDUCTOR', 'rol' => 'OPERATIVO']);
		DB::table('poblacion')->where('numdoc', '89005500')->update(['cargo' => 'DIRECTOR DE  TEGNOLOGIAS DE LA INFORMACION', 'rol' => 'ESTRATEGICO']);
    }
}
